### ISSUE TITLE
Add support for heater

### ISSUE THREAD

**Issue by ericbeecher1** [zyonse/homebridge-dreo#15]
Right now the heater type is not supported in this plugin, it would be great to be able to add it as a thermostat in homekit and enable heating when dropping below a certain temperature. I have the heater and would be happy to test anything you need! Right now when i install the plugin this is what the logs read: 

Adding new accessory: Heater
(node:19589) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'items' of undefined
    at new FanAccessory (/usr/lib/node_modules/homebridge-dreo/src/FanAccessory.ts:35:79)
    at DreoPlatform.discoverDevices (/usr/lib/node_modules/homebridge-dreo/src/platform.ts:150:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)

Thanks for your great work and your consideration of this request.

**Comment by zyonse** [comment]
Sorry for the lack of progress on this, can you launch homebridge in debug mode and post the console output here? (make sure you redact username/password)

**Comment by joshuaswilcox** [comment]
I confirm I get

```[11/10/2023, 11:37:15] [Dreo Platform] 

DEVICES:
 [
  {
    deviceId: '171212xxxxxxxxxxxx9969',
    sn: 'xxxxxxxxxxxxxxxxxxx',
    brand: 'Dreo',
    model: 'DR-HSH009S',
    productId: '1643940769442639873',
    productName: 'Heater',
    deviceName: 'Heater',
    shared: false,
    series: null,
    seriesName: 'Wall-mounted Heater',
    controlsConf: {
      template: 'DR-HSH009S',
      lottie: [Object],
      schedule: [Object],
      timer: [Object],
      cards: [Array],
      feature: [Object],
      preference: [Array],
      control: [Array],
      category: 'Space Heater',
      version: [Object]
    },
    mainConf: {
      isSmart: true,
      isWifi: true,
      isBluetooth: true,
      isVoiceControl: true
    },
    resourcesConf: {
      imageSmallSrc: 'https://resources.dreo-cloud.com/app/202306/20bad19da722a44238bb81ae3a6b87b689.png',
      imageFullSrc: 'https://resources.dreo-cloud.com/app/202307/259dd80ef20e50432195beab4dc1939160.zip',
      imageSmallDarkSrc: '',
      imageFullDarkSrc: ''
    },
    servicesConf: [ [Object] ],
    userManuals: [ [Object], [Object], [Object] ]
  }
]
[11/10/2023, 11:37:15] [Dreo Platform] wss://wsb-us.dreo-cloud.com/websocket?accessToken=TOKEN_REDACTED&timestamp=1697038635311
[11/10/2023, 11:37:15] [Dreo Platform] WebSocket Opened
[11/10/2023, 11:37:15] [Dreo Platform] Adding new accessory: Heater
TypeError: Cannot read properties of undefined (reading 'items')
    at new FanAccessory (/usr/local/lib/node_modules/homebridge-dreo/src/FanAccessory.ts:35:79)
    at DreoPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-dreo/src/platform.ts:150:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)```

**Comment by CappiSteijns** [comment]
Any updates on this? I am looking into buying the DR-HSH010 but would love to have it working within home assistant :)

**Comment by robotpants** [comment]
Hi ther, I just got the DR_HSH004S small heater. Would love to check in on progress here. Homekit was able to see it and call it "Heater" but it's just a blank tile in the app with no function. (My other fan worked great.)

**Comment by Bobmelon24** [comment]
Would like to second this proposal for a working heater function (could even just put it in an a fan with 100 different levels for each degree).

**Comment by ay8s** [comment]
@zyonse Just picked up a DR-HAC005S AC unit, I'd like to think it works pretty similar to the heater implementation. Happy to help test anything.

**Comment by Bobmelon24** [comment]
@zyonse Got a heater unit and would love if you could add a work around for the heater!

**Comment by zyonse** [comment]
@ay8s Can you update to v3.4.1 and post your logs with debug mode enabled?

**Comment by ay8s** [comment]
@zyonse Shout if there's anything additional I missed.

```
NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[13/10/2024, 21:37:10] Homebridge v1.8.4 (HAP v0.12.2) (Dreo Platform) is running on port 40221.
[13/10/2024, 21:37:10] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[13/10/2024, 21:37:11] [Dreo Platform] Country: US
[13/10/2024, 21:37:11] [Dreo Platform] Region: NA
[13/10/2024, 21:37:11] [Dreo Platform] 

Devices:
 [
	{
		deviceId: '********',
		sn: '********',
		brand: 'Dreo',
		model: 'DR-HAC005S',
		productId: '1706134985203331074',
		productName: 'Air Conditioner',
		deviceName: 'Air Conditioner',
		shared: false,
		series: null,
		seriesName: 'AC515S',
		type: 0,
		owner: true,
		familyId: null,
		familyName: null,
		roomId: null,
		roomName: null,
		roomNameI18Key: '',
		color: 'w',
		variantIconMd5: null,
		controlsConf: {
			template: 'DR-HAC005S',
			lottie: [Object],
			schedule: [Object],
			timer: [Object],
			cards: [Array],
			urlConfig: [Array],
			feature: [Object],
			preference: [Array],
			control: [Array],
			category: 'Air Conditioner',
			version: [Object]
		},
		mainConf: {
			isSmart: true,
			isWifi: true,
			isBluetooth: true,
			isVoiceControl: true
		},
		resourcesConf: {
			imageSmallSrc: 'https://resources.dreo-cloud.com/app/preSigned202409/116fb2836b69ff41d1af0aaaeca598f19f.png',
			imageFullSrc: 'https://resources.dreo-cloud.com/app/202402/20/a82251e0d1ab44d89b356a5dcea07f1a.zip',
			imageSmallDarkSrc: '',
			imageFullDarkSrc: ''
		},
		servicesConf: [ [Object] ],
		userManuals: [ [Object] ]
	}
]
[13/10/2024, 21:37:11] [Dreo Platform] wss://wsb-us.dreo-cloud.com/websocket?accessToken=xxxxxxxxxxxx&timestamp=1728880631569
[13/10/2024, 21:37:11] [Dreo Platform] Control parameters:  [
	{
		"id": "130",
		"type": "Speed",
		"title": "device_control_speed",
		"items": [
			{
				"text": "base_1",
				"cmd": "windlevel",
				"value": 1
			},
			{
				"text": "base_2",
				"cmd": "windlevel",
				"value": 2
			},
			{
				"text": "base_3",
				"cmd": "windlevel",
				"value": 3
			},
			{
				"text": "device_control_mode_auto",
				"cmd": "windlevel",
				"value": 4
			}
		]
	},
	{
		"id": "120",
		"type": "Oscillation",
		"title": "base_swing",
		"items": [],
		"cmd": "oscmode"
	}
]
[13/10/2024, 21:37:11] [Dreo Platform] Accessory state: {
	wifi_rssi: { state: -22, timestamp: 1728682890 },
	poweron: { state: false, timestamp: 1728857124 },
	scheid: { state: 0, timestamp: 1728682890 },
	timeron: { state: { du: 0, ts: 1728682889 }, timestamp: null },
	coolcruvendts: { state: 0, timestamp: 1728682890 },
	scheon: { state: false, timestamp: 1728682890 },
	mcuon: { state: true, timestamp: 1728682890 },
	templevel: { state: 77, timestamp: 1728689594 },
	mode: { state: 1, timestamp: 1728688199 },
	network_latency: { state: 76, timestamp: 1728682890 },
	rhlevel: { state: 60, timestamp: 1728682890 },
	module_hardware_model: { state: 'HeFi', timestamp: 1728682890 },
	mcu_firmware_version: { state: '1.0.72', timestamp: 1728682890 },
	oscmode: { state: 2, timestamp: 1728687951 },
	temperature: { state: 76, timestamp: 1728878314 },
	module_hardware_mac: { state: '001cc286115d', timestamp: 1728682890 },
	reachtarget: { state: 0, timestamp: 1728854085 },
	muteon: { state: false, timestamp: 1728687952 },
	lighton: { state: true, timestamp: 1728688560 },
	mcu_hardware_model: { state: 'SC95F8613B/US', timestamp: 1728682890 },
	wifi_ssid: { state: 'AndyDev', timestamp: 1728682890 },
	windlevel: { state: 2, timestamp: 1728689582 },
	tempunit: { state: 2, timestamp: 1728682890 },
	sleeptempoffset: { state: 0, timestamp: 1728682890 },
	module_firmware_version: { state: '3.2.16', timestamp: 1728682890 },
	wrong: { state: 0, timestamp: 1728682890 },
	connected: { state: true, timestamp: 1728682890 },
	timeroff: { state: { du: 0, ts: 1728682889 }, timestamp: null },
	_ota: { state: 2, timestamp: 1728682890 },
	filterthr: { state: 600, timestamp: 1728682890 },
	coolcurveconf: { state: 'NULL', timestamp: 1728682890 },
	rh: { state: 51, timestamp: 1728880485 },
	ecopauserate: { state: 0, timestamp: 1728682890 },
	childlockon: { state: false, timestamp: 1728682890 },
	worktime: { state: 1, timestamp: 1728687740 }
}
[13/10/2024, 21:37:11] [Dreo Platform] Restoring existing accessory from cache: Air Conditioner
[13/10/2024, 21:37:12] [Dreo Platform] WebSocket Opened
```

**Comment by joshuaswilcox** [comment]
Sorry for dropping on this, but I can test with my heater and make any updates to my initial pr if needed

**Comment by zyonse** [comment]
@joshuaswilcox I'm doing some restructuring to the device classes but if I end using part of your code I'll be sure to credit you in the release

**Comment by joshuaswilcox** [comment]
My logs are pretty much the same as @ay8s except its for `seriesName: 'Wall-mounted Heater',`

**Comment by joshuaswilcox** [comment]
@zyonse my logs were from 3.4.1, here are the full logs

```
[14/10/2024, 20:36:46] [Dreo Platform] Restarting child bridge...
[14/10/2024, 20:36:46] Got SIGTERM, shutting down child bridge process...
[14/10/2024, 20:36:52] [Dreo Platform] Child bridge process ended
[14/10/2024, 20:36:52] [Dreo Platform] Process Ended. Code: 143, Signal: null
[14/10/2024, 20:36:59] [Dreo Platform] Restarting Process...
[14/10/2024, 20:36:59] [Dreo Platform] Launched child bridge with PID 2141947
[14/10/2024, 20:36:59] Registering platform 'homebridge-dreo.DreoPlatform'
[14/10/2024, 20:36:59] [Dreo Platform] Loaded homebridge-dreo v3.4.1 child bridge successfully
[14/10/2024, 20:36:59] Loaded 1 cached accessories from cachedAccessories.0EE5174BC331.
[14/10/2024, 20:36:59] [Dreo Platform] Finished initializing platform: Dreo Platform
[14/10/2024, 20:36:59] [Dreo Platform] Loading accessory from cache: Heater
[14/10/2024, 20:37:00] Publishing bridge accessory (name: Dreo Platform, publishInfo: {
  username: '0E:E5:17:4B:C3:31',
  port: 30741,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'avahi'
}).
[14/10/2024, 20:37:00] [Dreo Platform] Executed didFinishLaunching callback
[14/10/2024, 20:37:00] Homebridge v1.8.4 (HAP v0.12.2) (Dreo Platform) is running on port 30741.
[14/10/2024, 20:37:00] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[14/10/2024, 20:37:00] [Dreo Platform] Country: US
[14/10/2024, 20:37:00] [Dreo Platform] Region: NA
[14/10/2024, 20:37:00] [Dreo Platform] 

Devices:
 [
  {
    deviceId: '********',
    sn: '********',
    brand: 'Dreo',
    model: 'DR-HSH009S',
    productId: '*************',
    productName: 'Heater',
    deviceName: 'Heater',
    shared: false,
    series: null,
    seriesName: 'Wall-mounted Heater',
    type: 0,
    owner: true,
    familyId: null,
    familyName: null,
    roomId: null,
    roomName: null,
    roomNameI18Key: '',
    color: 'w',
    variantIconMd5: null,
    controlsConf: {
      template: 'DR-HSH009S',
      lottie: [Object],
      schedule: [Object],
      timer: [Object],
      cards: [Array],
      feature: [Object],
      preference: [Array],
      control: [Array],
      category: 'Space Heater',
      version: [Object]
    },
    mainConf: {
      isSmart: true,
      isWifi: true,
      isBluetooth: true,
      isVoiceControl: true
    },
    resourcesConf: {
      imageSmallSrc: 'https://resources.dreo-cloud.com/app/preSigned202409/1102a14281ba5a4a878c4f0eaadf5cad6c.png',
      imageFullSrc: 'https://resources.dreo-cloud.com/app/202307/259dd80ef20e50432195beab4dc1939160.zip',
      imageSmallDarkSrc: '',
      imageFullDarkSrc: ''
    },
    servicesConf: [ [Object] ],
    userManuals: [ [Object], [Object], [Object] ]
  }
]
[14/10/2024, 20:37:00] [Dreo Platform] wss://wsb-us.dreo-cloud.com/websocket?accessToken=*****************&timestamp=1728952620732
[14/10/2024, 20:37:00] [Dreo Platform] Control parameters:  [
  {
    "swingtype": true,
    "hideSafeMode": true
  }
]
[14/10/2024, 20:37:00] [Dreo Platform] Accessory state: {
  lightsenon: { state: false, timestamp: 1728915805 },
  wifi_rssi: { state: -48, timestamp: 1728915805 },
  poweron: { state: true, timestamp: 1728915859 },
  scheid: { state: 0, timestamp: 1728915805 },
  timeron: { state: { du: 0, ts: 1728915804 }, timestamp: null },
  scheon: { state: false, timestamp: 1728915805 },
  mode: { state: 'eco', timestamp: 1728939425 },
  mcuon: { state: true, timestamp: 1728915805 },
  network_latency: { state: 49, timestamp: 1728915805 },
  module_hardware_model: { state: 'HeFi', timestamp: 1728915805 },
  mcu_firmware_version: { state: '1.0.80', timestamp: 1728915805 },
  otp_in_plug: { state: false, timestamp: 1728915805 },
  cooldown: { state: 0, timestamp: 1728915805 },
  temperature: { state: 58, timestamp: 1728940412 },
  winopened: { state: 0, timestamp: 1728915805 },
  frostproton: { state: false, timestamp: 1728915805 },
  winopenon: { state: false, timestamp: 1728915805 },
  module_hardware_mac: { state: '001cc26d7107', timestamp: 1728915805 },
  ptcon: { state: true, timestamp: 1728939429 },
  muteon: { state: false, timestamp: 1728915805 },
  mcu_hardware_model: { state: 'SC95F8613B', timestamp: 1728915805 },
  wifi_ssid: { state: 'Cocktails & Dreams III', timestamp: 1728915805 },
  tempunit: { state: 1, timestamp: 1728915805 },
  frostprotwk: { state: false, timestamp: 1728915805 },
  wrong: { state: 0, timestamp: 1728915805 },
  module_firmware_version: { state: '3.2.11', timestamp: 1728915805 },
  connected: { state: false, timestamp: 1728940980 },
  timeroff: { state: { du: 0, ts: 1728915804 }, timestamp: null },
  _ota: { state: 2, timestamp: 1728915805 },
  ledkepton: { state: true, timestamp: 1728915805 },
  ecolevel: { state: 62, timestamp: 1728939429 },
  frostprottemp: { state: 45, timestamp: 1728915805 },
  childlockon: { state: false, timestamp: 1728915805 },
  htalevel: { state: 3, timestamp: 1728915805 },
  dispmode: { state: 'level', timestamp: 1728915805 },
  oscangle: { state: 0, timestamp: 1728915805 },
  tempoffset: { state: 0, timestamp: 1728915805 }
}
[14/10/2024, 20:37:00] [Dreo Platform] Restoring existing accessory from cache: Heater
[14/10/2024, 20:37:00] [Dreo Platform] error: Unsupported device type  Heater
[14/10/2024, 20:37:01] [Dreo Platform] WebSocket Opened
```

**Comment by zyonse** [comment]
@ericbeecher1 @joshuaswilcox @Bobmelon24 @robotpants

Just released a new beta version with heater support (v4.0.0), please test and report back.

Most of the functionality from the app is implemented with the caveat that you can't use the static heating speeds, only the 'eco' mode where you set a target temperature. In the future I might add a separate fan accessory to control that if there's demand for it. It's just difficult to do with the limitations of HomeKit's APIs.

**Comment by zyonse** [comment]
@ay8s Can you open a new issue for AC support? The heater controls ended up being more complicated than I anticipated so I'm going to implement AC in a separate branch

**Comment by zyonse** [comment]
Small update, added support for static heating speeds via the thermostat 'auto' mode
