### ISSUE TITLE
Plug-in crashes when Humidifier added to account

### ISSUE THREAD

**Issue by arbnknight** [zyonse/homebridge-dreo#27]
**Describe The Bug:**
Added a humidifier device to my account. Since then the plug-in is caught in a restart loop and seems to bring the child bridge with it. 

**To Reproduce:**
add a Dreo 6L HM713S humidifier to your account and wait for the plug-in to poll for it. 

**Expected behavior:**
Filing a bug since plug in shouldn’t stop with humidifier added but should ignore it. I will file an enhancement separately for humidifier support (happy to help too). 

**Logs:**

```

[11/14/2023, 10:55:01 PM] [Dreo Platform] Adding new accessory: Humidifier
TypeError: Cannot read properties of undefined (reading '1')
    at new FanAccessory (/var/lib/homebridge/node_modules/homebridge-dreo/src/FanAccessory.ts:38:75)
    at DreoPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-dreo/src/platform.ts:150:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/14/2023, 10:55:01 PM] [Dreo Platform] Child bridge process ended
[11/14/2023, 10:55:01 PM] [Dreo Platform] Process Ended. Code: 1, Signal: null

```

**Plugin Config:**

```json

"hideTemperatureSensor": false,
            "temperatureOffset": 0,

```

**Screenshots:**

**Environment:**

* **Plugin Version**: 3.2.2
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by arbnknight** [comment]
Corresponding enhancement filed here: https://github.com/zyonse/homebridge-dreo/issues/28

**Comment by brentmw** [comment]
I get the same error. Is there a workaround? Or do I need to remove the humidifier from my Dreo account for the plugin to work?

**Comment by rizaus** [comment]
Same, bought the humidifier and wondered why my fan suddenly stopped working.

**Comment by zyonse** [comment]
@rizaus @brentmw @mja00 Please test v3.2.5-beta.0 and let me know if that fixes the crashing. You can install it by going to homebridge > plugins > homebridge-dreo > manage version
