### ISSUE TITLE
Having Dreo ChefMaker crashes plugin

### ISSUE THREAD

**Issue by iRonin** [zyonse/homebridge-dreo#29]
Dreo ChefMaker is pretty neat device but crashes the plugin - probably no support for it:

```
[18/11/2023, 8:25:52 pm] [Dreo Platform] Adding new accessory: ChefMaker
TypeError: Cannot read properties of undefined (reading '1')
    at new FanAccessory (/var/lib/homebridge/node_modules/homebridge-dreo/src/FanAccessory.ts:38:75)
    at DreoPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-dreo/src/platform.ts:150:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by zyonse** [comment]
This should be fixed once #30 is merged.
