### ISSUE TITLE
Failed to obtain access_token

### ISSUE THREAD

**Issue by Cerebellum-ITM** [zyonse/homebridge-dreo#34]
Hello, I haven't installed the plugin for a short time. But it has stopped working and I have found the error shown below. I fixed it by restarting the plugin. Is it because some configuration is missing on my part? Because I see that in theory you can turn on the ocillation but I can't find the option. Thanks in advance

**Logs:**

```
 cause: Error: getaddrinfo EAI_AGAIN app-api-us.dreo-cloud.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'app-api-us.dreo-cloud.com'
  }
}
[3/14/2024, 8:11:04 AM] [Dreo Platform] Authentication error: Failed to obtain access_token
```

**Comment by zyonse** [comment]
Are you able to reproduce the issue or did it just happen once?

**Comment by Cerebellum-ITM** [comment]
It happened to me 2 or 3 times but since the last time it has not failed again.

**Comment by Cerebellum-ITM** [comment]
I just passed by again. She solves it by restarting the dreo module. Add all error logs. (I deleted my personal information from the logs, well I hope)

``` bash
error retrieving token: AxiosError: getaddrinfo EAI_AGAIN app-api-us.dreo-cloud.com
    at Function.AxiosError.from (/homebridge/node_modules/homebridge-dreo/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/homebridge/node_modules/homebridge-dreo/node_modules/axios/lib/adapters/http.js:610:25)
    at RedirectableRequest.emit (node:events:518:28)
    at ClientRequest.eventHandlers.<computed> (/homebridge/node_modules/homebridge-dreo/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/homebridge/node_modules/homebridge-dreo/node_modules/axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DreoAPI.authenticate (/homebridge/node_modules/homebridge-dreo/src/DreoAPI.ts:11:5)
    at DreoPlatform.discoverDevices (/homebridge/node_modules/homebridge-dreo/src/platform.ts:69:16) {
  hostname: 'app-api-us.dreo-cloud.com',
  syscall: 'getaddrinfo',
  code: 'EAI_AGAIN',
  errno: -3001,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json; charset=UTF-8',
      ua: 'dreo/2.5.12 (sdk_gphone64_arm64;android 13;Scale/2.625)',
      lang: 'en',
      'accept-encoding': 'gzip',
      'user-agent': 'okhttp/4.9.1',
      'Content-Length': '291'
    },
    params: { timestamp: 1710965405221 },
    method: 'post',
    url: 'https://app-api-us.dreo-cloud.com/api/oauth/login',
    data: '{"client_id":"XXX","client_secret":"XXX","email":"XXX","encrypt":"ciphertext","grant_type":"email-password","himei":"XXX","password":"XXX","scope":"all"}'
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Function: handleRequestSocket]
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/api/oauth/login?timestamp=1710965405221',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'app-api-us.dreo-cloud.com',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/api/oauth/login',
      search: '?timestamp=1710965405221'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 291,
    _requestBodyBuffers: [ [Object] ],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '291',
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /api/oauth/login?timestamp=1710965405221 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json; charset=UTF-8\r\n' +
        'ua: dreo/2.5.12 (sdk_gphone64_arm64;android 13;Scale/2.625)\r\n' +
        'lang: en\r\n' +
        'accept-encoding: gzip\r\n' +
        'user-agent: okhttp/4.9.1\r\n' +
        'Content-Length: 291\r\n' +
        'Host: app-api-us.dreo-cloud.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/oauth/login?timestamp=1710965405221',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'app-api-us.dreo-cloud.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://app-api-us.dreo-cloud.com/api/oauth/login?timestamp=1710965405221',
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: Error: getaddrinfo EAI_AGAIN app-api-us.dreo-cloud.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'app-api-us.dreo-cloud.com'
  }
}
[3/20/2024, 2:10:18 PM] [Dreo Platform] Authentication error: Failed to obtain access_token
```

**Comment by zyonse** [comment]
Does the error occur when first starting the plugin or only after a certain amount of time passes?

**Comment by Cerebellum-ITM** [comment]
Sorry, I didn't see the message. It seems to be after a certain time
