### ISSUE TITLE
Error With Install - Websocket closed before connection established loop

### ISSUE THREAD

**Issue by AlbertEinslime** [zyonse/homebridge-dreo#35]
**Describe Your Problem:**
Attempted to install the plugin and enter my account login-credentials, however it seems to throw my homebridge into a loop and I cant seem to get it to function correctly. Tried my best to attach the relevant info below. Thanks.

**Logs:**

```
[26/03/2024, 11:22:47] Error: WebSocket was closed before the connection was established
    at WebSocket.close (/var/lib/homebridge/node_modules/homebridge-dreo/node_modules/ws/lib/websocket.js:292:7)
    at ReconnectingWebSocket._disconnect (/var/lib/homebridge/node_modules/homebridge-dreo/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:539:22)
    at ReconnectingWebSocket._handleError (/var/lib/homebridge/node_modules/homebridge-dreo/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:180:19)
    at ReconnectingWebSocket._handleTimeout (/var/lib/homebridge/node_modules/homebridge-dreo/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:14)
    at Timeout.<anonymous> (/var/lib/homebridge/node_modules/homebridge-dreo/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
[26/03/2024, 11:22:47] Got SIGTERM, shutting down Homebridge...
[26/03/2024, 11:22:47] Got SIGTERM, shutting down child bridge process...
```

**Plugin Config:**

```json
{
    "name": "Dreo Platform",
    "options": {
        "email": "s*********@*****.com",
        "password": "p*****************z"
    },
    "hideTemperatureSensor": false,
    "temperatureOffset": 0,
    "platform": "DreoPlatform"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 3.2.5
* **Homebridge Version**: v1.7.0
* **Node.js Version**: v20.11.1
* **NPM Version**: 7.5.2
* **Operating System**: Raspbian

**Comment by zyonse** [comment]
The websocket in general has a bunch of issues. I'm going to do some more digging into the API and see if there's a way to control devices with only http requests.
