### ISSUE TITLE
TypeError when retrieving device state

### ISSUE THREAD

**Issue by danjordan2** [zyonse/homebridge-dreo#47]
**Describe The Bug:**

After several months of working fine, I've suddenly started getting an error, and the plugin has stopped working.
```
[7/22/2024, 3:51:07 AM] [Dreo Platform] wss://wsb-us.dreo-cloud.com/websocket?accessToken=---&timestamp=1721620267176
[7/22/2024, 3:51:07 AM] [Dreo Platform] error retrieving device state: TypeError: Cannot read properties of undefined (reading 'mixed')
    at /var/lib/homebridge/node_modules/homebridge-dreo/src/DreoAPI.ts:94:36
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DreoAPI.getState (/var/lib/homebridge/node_modules/homebridge-dreo/src/DreoAPI.ts:80:5)
    at DreoPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-dreo/src/platform.ts:115:21)
[7/22/2024, 3:51:07 AM] [Dreo Platform] error: Failed to retrieve device state
[7/22/2024, 3:51:07 AM] [Dreo Platform] WebSocket Opened
``` 

**To Reproduce:**

Error occurs immediately after starting plugin.

**Expected behavior:**
Plugin should retrieve device status from Dreo API. 

**Logs:**
```
[7/22/2024, 3:51:06 AM] [Dreo Platform] Executed didFinishLaunching callback
[7/22/2024, 3:51:06 AM] Homebridge v1.8.4 (HAP v0.12.2) (Dreo Platform) is running on port 51195.
[7/22/2024, 3:51:06 AM] 

[7/22/2024, 3:51:07 AM] [Dreo Platform] 

REMOTE:
 {
  access_token: ---,
  refresh_token: ---',
  createdAt: 1696979232000,
  countryCode: 'US',
  scope: 'all',
  token_type: 'bearer',
  region: 'NA',
  expires_in: 303795999,
  userid: ---
}
[7/22/2024, 3:51:07 AM] [Dreo Platform] Country: US
[7/22/2024, 3:51:07 AM] [Dreo Platform] Region: NA
[7/22/2024, 3:51:07 AM] [Dreo Platform] 

DEVICES:
 [
  {
    deviceId:  ---,
    sn: ---,
    brand: 'Dreo',
    model: 'DR-HTF005S',
    productId: '1514165925956890625',
    productName: 'Tower Fan',
    deviceName: 'Tower Fan',
    shared: false,
    series: null,
    seriesName: 'Pilot Pro S',
    color: 's',
    controlsConf: {
      template: 'DR-HTF005S',
      lottie: [Object],
      schedule: [Object],
      cards: [Array],
      feature: [Object],
      preference: [Array],
      extraConfigs: [Array],
      control: [Array],
      category: 'Tower Fan',
      setting: [Array]
    },
    mainConf: {
      isSmart: true,
      isWifi: true,
      isBluetooth: true,
      isVoiceControl: true
    },
    resourcesConf: {
      imageSmallSrc: 'https://resources.dreo-cloud.com/app/preSigned202405/2302bbcd1232ac4326ae312abaa1cc6d70.png',
      imageFullSrc: 'https://resources.dreo-cloud.com/app/202309/863baa919beea413783c2c6400029eb39.zip',
      imageSmallDarkSrc: '',
      imageFullDarkSrc: ''
    },
    servicesConf: [ [Object] ],
    userManuals: [ [Object] ]
  },
  {
    deviceId: ---,
    sn: ---,
    brand: 'Dreo',
    model: 'DR-HTF005S',
    productId: '1514165925956890625',
    productName: 'Tower Fan',
    deviceName: ---,
    shared: false,
    series: null,
    seriesName: 'Pilot Pro S',
    color: 's',
    controlsConf: {
      template: 'DR-HTF005S',
      lottie: [Object],
      schedule: [Object],
      cards: [Array],
      feature: [Object],
      preference: [Array],
      extraConfigs: [Array],
      control: [Array],
      category: 'Tower Fan',
      setting: [Array]
    },
    mainConf: {
      isSmart: true,
      isWifi: true,
      isBluetooth: true,
      isVoiceControl: true
    },
    resourcesConf: {
      imageSmallSrc: 'https://resources.dreo-cloud.com/app/preSigned202405/2302bbcd1232ac4326ae312abaa1cc6d70.png',
      imageFullSrc: 'https://resources.dreo-cloud.com/app/202309/863baa919beea413783c2c6400029eb39.zip',
      imageSmallDarkSrc: '',
      imageFullDarkSrc: ''
    },
    servicesConf: [ [Object] ],
    userManuals: [ [Object] ]
  },
  {
    deviceId: ---,
    sn: ---,
    brand: 'Dreo',
    model: 'DR-HTF005S',
    productId: '1514165925956890625',
    productName: 'Tower Fan',
    deviceName: ---,
    shared: false,
    series: null,
    seriesName: 'Pilot Pro S',
    color: 's',
    controlsConf: {
      template: 'DR-HTF005S',
      lottie: [Object],
      schedule: [Object],
      cards: [Array],
      feature: [Object],
      preference: [Array],
      extraConfigs: [Array],
      control: [Array],
      category: 'Tower Fan',
      setting: [Array]
    },
    mainConf: {
      isSmart: true,
      isWifi: true,
      isBluetooth: true,
      isVoiceControl: true
    },
    resourcesConf: {
      imageSmallSrc: 'https://resources.dreo-cloud.com/app/preSigned202405/2302bbcd1232ac4326ae312abaa1cc6d70.png',
      imageFullSrc: 'https://resources.dreo-cloud.com/app/202309/863baa919beea413783c2c6400029eb39.zip',
      imageSmallDarkSrc: '',
      imageFullDarkSrc: ''
    },
    servicesConf: [ [Object] ],
    userManuals: [ [Object] ]
  }
]
[7/22/2024, 3:51:07 AM] [Dreo Platform] wss://wsb-us.dreo-cloud.com/websocket?accessToken=---&timestamp=1721620267176
[7/22/2024, 3:51:07 AM] [Dreo Platform] error retrieving device state: TypeError: Cannot read properties of undefined (reading 'mixed')
    at /var/lib/homebridge/node_modules/homebridge-dreo/src/DreoAPI.ts:94:36
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DreoAPI.getState (/var/lib/homebridge/node_modules/homebridge-dreo/src/DreoAPI.ts:80:5)
    at DreoPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-dreo/src/platform.ts:115:21)
[7/22/2024, 3:51:07 AM] [Dreo Platform] error: Failed to retrieve device state
[7/22/2024, 3:51:07 AM] [Dreo Platform] WebSocket Opened

```

**Environment:**

* **Plugin Version**: v3.3.1-beta.1
* **Homebridge Version**: v1.8.4
* **Node.js Version**: v20.12.2
* **NPM Version**: 10.5.0
* **Operating System**: Debian

**Comment by zyonse** [comment]
Does this happen on the latest stable version or just the beta?

**Comment by danjordan2** [comment]
It happens on the latest stable version as well. I only updated to the beta to see if this had been fixed in there. This issue started happening about 4 days ago.

**Comment by zyonse** [comment]
How many devices do you have on your Dreo account?

**Comment by danjordan2** [comment]
3

**Comment by danjordan2** [comment]
There must have been an api change on Dreo's end. Everything has started working again (same with my homeassistant dreo integration, which was throwing a similar error).

**Comment by zyonse** [comment]
Thanks for the update, was having trouble reproducing this. Please comment on this thread if you run into the issue again.
