### ISSUE TITLE
Not working with Falcon S (DR-HAF004S)

### ISSUE THREAD

**Issue by Jozer99** [zyonse/homebridge-dreo#5]
**Describe Your Problem:**
When I install the plugin and sign in, my fan does not show up.  

**Logs:**

```
[02/06/2023, 21:19:56] [Dreo Platform] Adding new accessory: Air Circulator
[02/06/2023, 21:19:56] TypeError: Cannot read properties of undefined (reading 'state')
    at new FanAccessory (/var/lib/homebridge/node_modules/homebridge-dreo/src/FanAccessory.ts:40:46)
    at DreoPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-dreo/src/platform.ts:150:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[02/06/2023, 21:19:56] Got SIGTERM, shutting down Homebridge...
```

**Plugin Config:**
        {
            "options": {
                "email": "[redacted]",
                "password": "[redacted]"
            },
            "name": "Dreo Platform",
            "platform": "DreoPlatform"
        }

**Screenshots:**

**Environment:**

* **Plugin Version**: c2.0.2
* **Homebridge Version**: 1.6.1
* **Node.js Version**: v18.16.0
* **NPM Version**: Whatever comes with Homebridge 1.6.1
* **Operating System**: Official Homebridge raspberry pi image

**Comment by zyonse** [comment]
Thanks for the bug report. Can you restart homebridge in debug mode and upload the console output again. (redact info as needed).

**Comment by Jozer99** [comment]
Here is the same error with debug mode enabled:

```
[04/06/2023, 00:12:46] [Dreo Platform] Adding new accessory: Air Circulator
[04/06/2023, 00:12:46] [Dreo Platform] {
  mcu_hardware_model: { state: 'SC95F8613B', timestamp: 1685315493 },
  wifi_ssid: { state: '[REDACTED]', timestamp: 1685315493 },
  windlevel: { state: 3, timestamp: 1685845780 },
  wifi_rssi: { state: -51, timestamp: 1685845780 },
  poweron: { state: true, timestamp: 1685845780 },
  tempunit: { state: 1, timestamp: 1685845780 },
  timeron: { state: { du: 0, ts: 1685315492 }, timestamp: null },
  module_firmware_version: { state: '1.2.12', timestamp: 1685845780 },
  mode: { state: 1, timestamp: 1685845780 },
  mcuon: { state: true, timestamp: 1685315493 },
  connected: { state: true, timestamp: 1685845780 },
  timeroff: { state: { du: 0, ts: 1685315492 }, timestamp: null },
  network_latency: { state: 166, timestamp: 1685845780 },
  module_hardware_model: { state: 'PAI-051', timestamp: 1685845780 },
  mcu_firmware_version: { state: '1.0.16', timestamp: 1685315493 },
  customconf: { state: 'temp:1111122222233333344444', timestamp: 1685845780 },
  ledkepton: { state: false, timestamp: 1685845780 },
  temperature: { state: 67, timestamp: 1685851909 },
  module_hardware_mac: { state: '[REDACTED]', timestamp: 1685845780 },
  childlockon: { state: false, timestamp: 1685845780 },
  muteon: { state: true, timestamp: 1685845780 },
  hoscon: { state: false, timestamp: 1685845780 }
}
[04/06/2023, 00:12:46] TypeError: Cannot read properties of undefined (reading 'state')
    at new FanAccessory (/var/lib/homebridge/node_modules/homebridge-dreo/src/FanAccessory.ts:40:46)
    at DreoPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-dreo/src/platform.ts:150:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by zyonse** [comment]
It seems to be caused by this model's lack of rotation control. I'll add some checks in the code to account for that.

**Comment by zyonse** [comment]
This should be fixed in v2.1.0, let me know if you have any issues.

**Comment by Jozer99** [comment]
Been testing for several days seems to work fine now.

**Comment by kapps7** [comment]
Hi 
I have 2 x DR-HAF004S. The fans connects into Homekit fine but oscillation control is not available. I am running the latest firmware and add-on versions. Can I provide any logs to you for assistance ?
Thanks
