### ISSUE TITLE
Fails to add new heater accessory

### ISSUE THREAD

**Issue by Dani3lSun** [zyonse/homebridge-dreo#55]
**Describe The Bug:**
Just added a new heater via the dreo app ( dreo atom one ) and afterwards tried to restart homebridge so the new heater is added there as well. But homebridge is then in a reboot loop failing to add this new accessory.

**To Reproduce:**
1. Add Dreo heater via app
2. Restart homebridge

**Expected behavior:**
Should not fail adding a new heater accessory.

**Logs:**

```
[10/23/2024, 2:54:19 PM] [Dreo Platform] Adding new accessory: Heizlüfter
[10/23/2024, 2:54:20 PM] TypeError: Cannot read properties of undefined (reading 'state')
    at new HeaterAccessory (/homebridge/node_modules/homebridge-dreo/src/accessories/HeaterAccessory.ts:61:24)
    at DreoPlatform.discoverDevices (/homebridge/node_modules/homebridge-dreo/src/platform.ts:183:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/23/2024, 2:54:20 PM] Got SIGTERM, shutting down Homebridge...
[10/23/2024, 2:54:20 PM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1004:11)
    at Server.setServerStatus (/homebridge/node_modules/homebridge/src/server.ts:143:45)
    at Server.teardown (/homebridge/node_modules/homebridge/src/server.ts:187:10)
    at signalHandler (/homebridge/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:531:35)
    at process.emit (/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
```

**Plugin Config:**

```json
{
    "name": "Dreo Platform",
    "options": {
        "email": "xxx",
        "password": "xxx"
    },
    "hideTemperatureSensor": true,
    "temperatureOffset": 0,
    "platform": "DreoPlatform"
}
```

**Environment:**

* **Plugin Version**: v4.0.1
* **Homebridge Version**: v1.8.4
* **Node.js Version**: v20.18.0
* **NPM Version**: v10.8.2
* **Operating System**: Docker

**Comment by zyonse** [comment]
@Dani3lSun Can you run homebridge in debug mode and post the output here? Also, what oscillation options does your heater have in the Dreo app?

**Comment by Dani3lSun** [comment]
Hi @zyonse thanks for the fast reply!

Here's the dreo plugin specific debug output:

```
[10/23/2024, 9:02:33 PM] [HB Supervisor] OS: Linux 6.1.0-26-amd64 x64
[10/23/2024, 9:02:33 PM] [HB Supervisor] Node.js v20.18.0 /opt/homebridge/bin/node
[10/23/2024, 9:02:33 PM] [HB Supervisor] Homebridge Path: /var/lib/homebridge/node_modules/homebridge/bin/homebridge
[10/23/2024, 9:02:33 PM] [HB Supervisor] UI Path: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[10/23/2024, 9:02:34 PM] [Homebridge UI] Homebridge UI v4.62.0 is listening on :: port 8581
[10/23/2024, 9:02:34 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules -D --strict-plugin-resolution
[10/23/2024, 9:02:34 PM] [HB Supervisor] Started Homebridge v1.8.4 with PID: 11724
[10/23/2024, 9:02:34 PM] Loaded config.json with 4 accessories and 5 platforms.
[10/23/2024, 9:02:34 PM] Loaded 1 cached accessories from cachedAccessories.
[10/23/2024, 9:02:34 PM] ---
[10/23/2024, 9:02:34 PM] Loaded plugin: homebridge-dreo@4.0.1
[10/23/2024, 9:02:34 PM] Registering platform 'homebridge-dreo.DreoPlatform'
[10/23/2024, 9:02:34 PM] ---
[10/23/2024, 9:02:34 PM] Loading 5 platforms...
[10/23/2024, 9:02:34 PM] [Dreo Platform] Initializing DreoPlatform platform...
[10/23/2024, 9:02:34 PM] [Dreo Platform] Finished initializing platform: Dreo Platform
[10/23/2024, 9:02:34 PM] [Dreo Platform] Executed didFinishLaunching callback

[10/23/2024, 9:02:35 PM] [Dreo Platform] Country: DE
[10/23/2024, 9:02:35 PM] [Dreo Platform] Region: EU
[10/23/2024, 9:02:35 PM] [Dreo Platform] 

Devices:
 [
  {
    deviceId: '********',
    sn: '********',
    brand: 'Dreo',
    model: 'DR-HSH004S',
    productId: '1536529638074978306',
    productName: 'Heater',
    deviceName: 'Heizlüfter',
    shared: false,
    series: null,
    seriesName: 'Atom One S',
    type: 0,
    owner: true,
    familyId: null,
    familyName: null,
    roomId: null,
    roomName: null,
    roomNameI18Key: '',
    color: 'b',
    variantIconMd5: null,
    controlsConf: {
      template: 'DR-HSH004S',
      lottie: [Object],
      instructions: [Object],
      cards: [Array],
      preference: [Array],
      control: [Array],
      category: 'Space Heater'
    },
    mainConf: {
      isSmart: true,
      isWifi: true,
      isBluetooth: true,
      isVoiceControl: true
    },
    resourcesConf: {
      imageSmallSrc: 'https://resources.dreo-cloud.com/app/preSigned202409/1127e0097ddfd14914abcce4fed5e7d36e.png',
      imageFullSrc: 'https://resources.dreo-cloud.com/app/preSigned202406/288eb1e27a155b4b4c875393b04313706a.zip',
      imageSmallDarkSrc: '',
      imageFullDarkSrc: ''
    },
    servicesConf: [ [Object] ],
    userManuals: [ [Object], [Object] ]
  },
  {
    deviceId: '********',
    sn: '********',
    brand: 'Dreo',
    model: 'DR-HTF004S',
    productId: '1453300621256003586',
    productName: 'Tower Fan',
    deviceName: 'Ventilator',
    shared: false,
    series: null,
    seriesName: 'Pilot Max S',
    type: 0,
    owner: true,
    familyId: null,
    familyName: null,
    roomId: null,
    roomName: null,
    roomNameI18Key: '',
    color: 's',
    variantIconMd5: null,
    controlsConf: {
      template: 'DR-HTF004S',
      lottie: [Object],
      schedule: [Object],
      cards: [Array],
      feature: [Object],
      preference: [Array],
      control: [Array],
      category: 'Tower Fan',
      setting: [Array]
    },
    mainConf: {
      isSmart: true,
      isWifi: true,
      isBluetooth: true,
      isVoiceControl: true
    },
    resourcesConf: {
      imageSmallSrc: 'https://resources.dreo-cloud.com/app/preSigned202409/112232278eb6c34e769765e1b31170a8ca.png',
      imageFullSrc: 'https://resources.dreo-cloud.com/app/202309/81dff85f94e94402785a26a33c340a16b.zip',
      imageSmallDarkSrc: '',
      imageFullDarkSrc: ''
    },
    servicesConf: [ [Object] ],
    userManuals: [ [Object] ]
  }
]
[10/23/2024, 9:02:35 PM] [Dreo Platform] Control config:  {
  "template": "DR-HSH004S",
  "lottie": {
    "key": "poweron",
    "frames": [
      {
        "value": 0,
        "frame": [
          0
        ]
      },
      {
        "value": 1,
        "frame": [
          2
        ]
      }
    ]
  },
  "instructions": {
    "en": "https://fe.dreo.com/en/safety-protection-instructions/",
    "zh": "https://fe.dreo.com/zh/safety-protection-instructions/"
  },
  "cards": [
    {
      "type": 2,
      "title": "device_control_temp",
      "icon": "",
      "image": "",
      "url": "",
      "show": true
    },
    {
      "type": 6,
      "title": "device_settings_title",
      "icon": "ic_setting",
      "image": "",
      "url": "dreo://nav/device/setting?deviceSn=${sn}",
      "show": true,
      "key": "setting"
    }
  ],
  "preference": [
    {
      "id": "200",
      "type": "Panel Sound",
      "title": "device_control_panelsound",
      "image": "ic_mute",
      "reverse": true,
      "cmd": "muteon"
    },
    {
      "id": "210",
      "type": "Display Auto Off",
      "title": "device_fans_mode_auto_display",
      "image": "ic_display",
      "reverse": true,
      "cmd": "lighton"
    },
    {
      "id": "220",
      "type": "Child Lock",
      "title": "device_control_childlock",
      "image": "ic_child_lock",
      "reverse": false,
      "cmd": "childlockon"
    },
    {
      "id": "230",
      "type": "Temperature Unit",
      "title": "device_control_temp_unit",
      "image": "ic_temp_unit"
    },
    {
      "id": "240",
      "type": "Temperature Calibration",
      "title": "device_control_temp_calibration",
      "image": "ic_temp_cal"
    }
  ],
  "control": [
    {
      "swingtype": false,
      "hideSafeMode": false
    }
  ],
  "category": "Space Heater"
}
[10/23/2024, 9:02:35 PM] [Dreo Platform] Adding new accessory: Heizlüfter
[10/23/2024, 9:02:35 PM] [Dreo Platform] Accessory state: {
  wifi_rssi: { state: -41, timestamp: 1729687355 },
  poweron: { state: false, timestamp: 1729688512 },
  devon: { state: true, timestamp: 1729687355 },
  scheid: { state: 0, timestamp: 1729687355 },
  timeron: { state: { du: 0, ts: 1729687356 }, timestamp: null },
  scheon: { state: false, timestamp: 1729687355 },
  oscon: { state: true, timestamp: 1729687430 },
  mcuon: { state: true, timestamp: 1729687355 },
  mode: { state: 'hotair', timestamp: 1729687355 },
  network_latency: { state: 7, timestamp: 1729687355 },
  module_hardware_model: { state: 'HeFi', timestamp: 1729687355 },
  mcu_firmware_version: { state: '0.1.2', timestamp: 1729687355 },
  temperature: { state: 72, timestamp: 1729699940 },
  cooldown: { state: 0, timestamp: 1729688542 },
  module_hardware_mac: { state: '001cc28a75ce', timestamp: 1729687355 },
  ptcon: { state: false, timestamp: 1729688512 },
  muteon: { state: false, timestamp: 1729687355 },
  lstrmtopat: { state: 0, timestamp: 1729687355 },
  lighton: { state: false, timestamp: 1729687355 },
  fstrmtopat: { state: 0, timestamp: 1729687355 },
  mcu_hardware_model: { state: 'SC95F8613B/EU', timestamp: 1729687355 },
  wifi_ssid: { state: 'UniFi Home', timestamp: 1729687355 },
  ctlstatus: { state: '', timestamp: 1729687355 },
  tempunit: { state: 0, timestamp: 1729687355 },
  module_firmware_version: { state: '3.2.5', timestamp: 1729687355 },
  wrong: { state: 0, timestamp: 1729687355 },
  connected: { state: true, timestamp: 1729687355 },
  timeroff: { state: { du: 0, ts: 1729687356 }, timestamp: null },
  _ota: { state: 0, timestamp: 1729687355 },
  ecolevel: { state: 85, timestamp: 1729687355 },
  childlockon: { state: false, timestamp: 1729687355 },
  htalevel: { state: 2, timestamp: 1729687428 },
  tempoffset: { state: 0, timestamp: 1729687355 }
}
[10/23/2024, 9:02:35 PM] TypeError: Cannot read properties of undefined (reading 'state')
    at new HeaterAccessory (/homebridge/node_modules/homebridge-dreo/src/accessories/HeaterAccessory.ts:61:24)
    at DreoPlatform.discoverDevices (/homebridge/node_modules/homebridge-dreo/src/platform.ts:183:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/23/2024, 9:02:35 PM] Got SIGTERM, shutting down Homebridge...
[10/23/2024, 9:02:35 PM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1004:11)
    at Server.setServerStatus (/homebridge/node_modules/homebridge/src/server.ts:143:45)
    at Server.teardown (/homebridge/node_modules/homebridge/src/server.ts:187:10)
    at signalHandler (/homebridge/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:531:35)
    at process.emit (/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[10/23/2024, 9:02:35 PM] Got SIGTERM, shutting down child bridge process...
[10/23/2024, 9:02:35 PM] [Dreo Platform] WebSocket Opened
[10/23/2024, 9:02:40 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[10/23/2024, 9:02:45 PM] [HB Supervisor] Restarting Homebridge...
```

Inside the app I really can only enable or disable oscillation, but no angle or so can be adjusted, see attached screen shot.

![PHOTO-2024-10-23-21-16-40](https://github.com/user-attachments/assets/4e36450a-8909-44b3-b86e-4fc4d0fc116b)

Thanks!

**Comment by zyonse** [comment]
Can you test the beta version I just published?

<img width="1226" alt="image" src="https://github.com/user-attachments/assets/c61e818e-b359-47e6-8c0e-1f1e6c17cc0e">

**Comment by Dani3lSun** [comment]
It's getting further now, and `state.oscangle` is not the issue anymore it seems, now it missed something with the schedule modes:

```
[10/23/2024, 10:44:44 PM] TypeError: Cannot read properties of undefined (reading 'modes')
    at new HeaterAccessory (/homebridge/node_modules/homebridge-dreo/src/accessories/HeaterAccessory.ts:122:69)
    at DreoPlatform.discoverDevices (/homebridge/node_modules/homebridge-dreo/src/platform.ts:183:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/23/2024, 10:44:44 PM] Got SIGTERM, shutting down Homebridge...
[10/23/2024, 10:44:45 PM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1004:11)
    at Server.setServerStatus (/homebridge/node_modules/homebridge/src/server.ts:143:45)
    at Server.teardown (/homebridge/node_modules/homebridge/src/server.ts:187:10)
    at signalHandler (/homebridge/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:531:35)
    at process.emit (/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
```

**Comment by simonrb2000** [comment]
I'm getting this too when trying to add Heater

```
[23/10/2024, 23:30:58] [Dreo Platform] Loaded homebridge-dreo v4.0.2-beta.0 child bridge successfully
[23/10/2024, 23:30:58] Loaded 0 cached accessories from cachedAccessories.0EE966FCC102.
[23/10/2024, 23:30:58] Homebridge v1.8.4 (HAP v0.12.2) (Dreo Platform) is running on port 38415.
[23/10/2024, 23:30:58] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[23/10/2024, 23:30:59] [Dreo Platform] Country: GB
[23/10/2024, 23:30:59] [Dreo Platform] Region: EU
[23/10/2024, 23:30:59] [Dreo Platform] Adding new accessory: Heater
TypeError: Cannot read properties of undefined (reading 'modes')
    at new HeaterAccessory (/var/lib/homebridge/node_modules/homebridge-dreo/src/accessories/HeaterAccessory.ts:122:69)
    at DreoPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-dreo/src/platform.ts:183:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/10/2024, 23:30:59] [Dreo Platform] Child bridge process ended
[23/10/2024, 23:30:59] [Dreo Platform] Process Ended. Code: 1, Signal: null
[23/10/2024, 23:31:06] [Dreo Platform] Restarting Process...
[23/10/2024, 23:31:08] [Dreo Platform] Launched child bridge with PID 19892
[23/10/2024, 23:31:08] Registering platform 'homebridge-dreo.DreoPlatform'
```

**Comment by zyonse** [comment]
@simonrb2000 What model? Can you post logs in debug mode

**Comment by simonrb2000** [comment]
Of course.. it's an Atom One Space Heater

```
[23/10/2024, 23:38:37] [Dreo Platform] Executed didFinishLaunching callback
[23/10/2024, 23:38:37] Homebridge v1.8.4 (HAP v0.12.2) (Dreo Platform) is running on port 38415.
[23/10/2024, 23:38:37] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[23/10/2024, 23:38:38] [Dreo Platform] Country: GB
[23/10/2024, 23:38:38] [Dreo Platform] Region: EU
[23/10/2024, 23:38:38] [Dreo Platform] 

Devices:
 [
  {
    deviceId: '********',
    sn: '********',
    brand: 'Dreo',
    model: 'DR-HSH004S',
    productId: '1536529638074978306',
    productName: 'Heater',
    deviceName: 'Heater',
    shared: false,
    series: null,
    seriesName: 'Atom One S',
    type: 0,
    owner: true,
    familyId: null,
    familyName: null,
    roomId: null,
    roomName: null,
    roomNameI18Key: '',
    color: 'b',
    variantIconMd5: null,
    controlsConf: {
      template: 'DR-HSH004S',
      lottie: [Object],
      instructions: [Object],
      cards: [Array],
      preference: [Array],
      control: [Array],
      category: 'Space Heater'
    },
    mainConf: {
      isSmart: true,
      isWifi: true,
      isBluetooth: true,
      isVoiceControl: true
    },
    resourcesConf: {
      imageSmallSrc: 'https://resources.dreo-cloud.com/app/preSigned202409/1127e0097ddfd14914abcce4fed5e7d36e.png',
      imageFullSrc: 'https://resources.dreo-cloud.com/app/preSigned202406/288eb1e27a155b4b4c875393b04313706a.zip',
      imageSmallDarkSrc: '',
      imageFullDarkSrc: ''
    },
    servicesConf: [ [Object] ],
    userManuals: [ [Object], [Object] ]
  }
]
[23/10/2024, 23:38:38] [Dreo Platform] Control config:  {
  "template": "DR-HSH004S",
  "lottie": {
    "key": "poweron",
    "frames": [
      {
        "value": 0,
        "frame": [
          0
        ]
      },
      {
        "value": 1,
        "frame": [
          2
        ]
      }
    ]
  },
  "instructions": {
    "en": "https://fe.dreo.com/en/safety-protection-instructions/",
    "zh": "https://fe.dreo.com/zh/safety-protection-instructions/"
  },
  "cards": [
    {
      "type": 2,
      "title": "device_control_temp",
      "icon": "",
      "image": "",
      "url": "",
      "show": true
    },
    {
      "type": 6,
      "title": "device_settings_title",
      "icon": "ic_setting",
      "image": "",
      "url": "dreo://nav/device/setting?deviceSn=${sn}",
      "show": true,
      "key": "setting"
    }
  ],
  "preference": [
    {
      "id": "200",
      "type": "Panel Sound",
      "title": "device_control_panelsound",
      "image": "ic_mute",
      "reverse": true,
      "cmd": "muteon"
    },
    {
      "id": "210",
      "type": "Display Auto Off",
      "title": "device_fans_mode_auto_display",
      "image": "ic_display",
      "reverse": true,
      "cmd": "lighton"
    },
    {
      "id": "220",
      "type": "Child Lock",
      "title": "device_control_childlock",
      "image": "ic_child_lock",
      "reverse": false,
      "cmd": "childlockon"
    },
    {
      "id": "230",
      "type": "Temperature Unit",
      "title": "device_control_temp_unit",
      "image": "ic_temp_unit"
    },
    {
      "id": "240",
      "type": "Temperature Calibration",
      "title": "device_control_temp_calibration",
      "image": "ic_temp_cal"
    }
  ],
  "control": [
    {
      "swingtype": false,
      "hideSafeMode": false
    }
  ],
  "category": "Space Heater"
}
[23/10/2024, 23:38:38] [Dreo Platform] Adding new accessory: Heater
[23/10/2024, 23:38:38] [Dreo Platform] Accessory state: {
  wifi_rssi: { state: -54, timestamp: 1729719656 },
  poweron: { state: false, timestamp: 1729722183 },
  devon: { state: true, timestamp: 1729719656 },
  scheid: { state: 0, timestamp: 1729719656 },
  timeron: { state: { du: 0, ts: 1729719654 }, timestamp: null },
  scheon: { state: false, timestamp: 1729719656 },
  oscon: { state: true, timestamp: 1729719775 },
  mcuon: { state: true, timestamp: 1729719656 },
  mode: { state: 'eco', timestamp: 1729719705 },
  network_latency: { state: 75, timestamp: 1729719656 },
  module_hardware_model: { state: 'HeFi', timestamp: 1729719656 },
  mcu_firmware_version: { state: '0.1.2', timestamp: 1729719656 },
  temperature: { state: 68, timestamp: 1729722515 },
  cooldown: { state: 0, timestamp: 1729719841 },
  module_hardware_mac: { state: '001cc28a771e', timestamp: 1729719656 },
  ptcon: { state: false, timestamp: 1729720555 },
  muteon: { state: false, timestamp: 1729719656 },
  lstrmtopat: { state: 0, timestamp: 1729719656 },
  lighton: { state: false, timestamp: 1729719656 },
  fstrmtopat: { state: 0, timestamp: 1729719656 },
  mcu_hardware_model: { state: 'SC95F8613B/EU', timestamp: 1729719656 },
  wifi_ssid: { state: 'Home', timestamp: 1729719656 },
  ctlstatus: { state: '', timestamp: 1729719656 },
  tempunit: { state: 0, timestamp: 1729719656 },
  module_firmware_version: { state: '3.2.5', timestamp: 1729719656 },
  wrong: { state: 0, timestamp: 1729719656 },
  connected: { state: true, timestamp: 1729719656 },
  timeroff: { state: { du: 0, ts: 1729719654 }, timestamp: null },
  _ota: { state: 0, timestamp: 1729719656 },
  ecolevel: { state: 68, timestamp: 1729719805 },
  childlockon: { state: false, timestamp: 1729719656 },
  htalevel: { state: 1, timestamp: 1729719656 },
  tempoffset: { state: 0, timestamp: 1729719656 }
}
TypeError: Cannot read properties of undefined (reading 'modes')
    at new HeaterAccessory (/var/lib/homebridge/node_modules/homebridge-dreo/src/accessories/HeaterAccessory.ts:122:69)
    at DreoPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-dreo/src/platform.ts:183:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23/10/2024, 23:38:38] [Dreo Platform] Child bridge process ended
[23/10/2024, 23:38:38] [Dreo Platform] Process Ended. Code: 1, Signal: null
[23/10/2024, 23:38:45] [Dreo Platform] Restarting Process...
[23/10/2024, 23:38:47] [Dreo Platform] Launched child bridge with PID 23915
[23/10/2024, 23:38:47] Registering platform 'homebridge-dreo.DreoPlatform'
[23/10/2024, 23:38:47] [Dreo Platform] Loaded homebridge-dreo v4.0.2-beta.0 child bridge successfully
[23/10/2024, 23:38:47] Loaded 0 cached accessories from cachedAccessories.0EE966FCC102.
[23/10/2024, 23:38:47] [Dreo Platform] Finished initializing platform: Dreo Platform
[23/10/2024, 23:38:47] Publishing bridge accessory (name: Dreo Platform, publishInfo: {
  username: '0E:E9:66:FC:C1:02',
  port: 38415,
  pincode: '***-**-***',
  category: 2,
  bind: [ 'eth0', [length]: 1 ],
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: undefined
}).
[23/10/2024, 23:38:47] [Dreo Platform] Executed didFinishLaunching callback
[23/10/2024, 23:38:47] Homebridge v1.8.4 (HAP v0.12.2) (Dreo Platform) is running on port 38415.
[23/10/2024, 23:38:47] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[23/10/2024, 23:38:48] [Dreo Platform] Country: GB
[23/10/2024, 23:38:48] [Dreo Platform] Region: EU
[23/10/2024, 23:38:48] [Dreo Platform] 

Devices:
 [
  {
    deviceId: '********',
    sn: '********',
    brand: 'Dreo',
    model: 'DR-HSH004S',
    productId: '1536529638074978306',
    productName: 'Heater',
    deviceName: 'Heater',
    shared: false,
    series: null,
    seriesName: 'Atom One S',
    type: 0,
    owner: true,
    familyId: null,
    familyName: null,
    roomId: null,
    roomName: null,
    roomNameI18Key: '',
    color: 'b',
    variantIconMd5: null,
    controlsConf: {
      template: 'DR-HSH004S',
      lottie: [Object],
      instructions: [Object],
```

**Comment by zyonse** [comment]
Can you test latest beta?

**Comment by Dani3lSun** [comment]
Thanks for your fast support. Works for me now 👍

**Comment by simonrb2000** [comment]
> Can you test latest beta? Just published a new one.

It’s working! Thank you! That was mega fast.

**Comment by zyonse** [comment]
Great to hear! Just wanted to check one more thing, is the "fan speed" option visible in your device settings? It should be disabled since your device doesn't support that feature.

<img width="379" alt="Screenshot 2024-10-23 at 7 03 32 PM" src="https://github.com/user-attachments/assets/4e5d7fc9-4cdf-4203-b473-8479084a787e">

**Comment by Dani3lSun** [comment]
Nope not visible for me

![image](https://github.com/user-attachments/assets/a400b012-b12b-4804-8f5e-37ffe208d6ed)

**Comment by zyonse** [comment]
Perfect, thanks for the help getting this fixed
