### ISSUE TITLE
Adding Support For Dreo Air Purifier (DR-HAP003S) 

### ISSUE THREAD

**Issue by dzslasher** [zyonse/homebridge-dreo#8]
I would love to see support for the Dreo Air Purifier specifically model DR-HAP003S.

**Comment by zyonse** [comment]
Can you post a screenshot of the device controls in the app?

**Comment by dzslasher** [comment]
![IMG_3114](https://github.com/zyonse/homebridge-dreo/assets/54277158/110fd3b3-ca01-4ad1-b092-16fe78cec17e)
![IMG_3113](https://github.com/zyonse/homebridge-dreo/assets/54277158/4e782fec-665e-4422-9697-712cafca6493)

**Comment by dzslasher** [comment]
Please see attached. It should show the logs for the Dreo Tower Fan and the Air Purifier. 
[Dreo Debug 06102023.zip](https://github.com/zyonse/homebridge-dreo/files/11713324/Dreo.Debug.06102023.zip)

**Comment by mark3apps** [comment]
I would love for this to be added.  It worked previously but since v4, now it's causing the plugin to crash every time.  I would love to give you an information that would be help for you to add this in.

**Comment by zyonse** [comment]
What error message are you getting?

**Comment by spaceottr** [comment]
Also worked previously for me (with exception to "Turbo" mode not being handled by HomeKit).  It broke but not sure if this is the same error others are receiving.  It successfully loads a fan before failing on the air purifier.  I have the air purifier model listed in the topic (DR-HAP003S).  Otherwise, this plugin works great with the fans.  Thank you!

[11/19/2024, 9:33:30 AM] [Dreo Platform] Restoring existing accessory from cache: Tower Fan LR
[11/19/2024, 9:33:30 AM] [Dreo Platform] Adding new accessory: Air Purifier LR
TypeError: Cannot read properties of undefined (reading 'items')
    at new FanAccessory (/usr/local/lib/node_modules/homebridge-dreo/src/accessories/FanAccessory.ts:37:116)
    at DreoPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-dreo/src/platform.ts:174:11)

**Comment by david-goodermote** [comment]
Any update on this? I am having a similar issue. 

[13/04/2025, 16:56:32] [Dreo Platform] Adding new accessory: Air Purifier
[13/04/2025, 16:56:33] [Dreo Platform] Accessory state: {
  lightsenon: { state: false, timestamp: 1744515556 },
  epmon: { state: false, timestamp: 1742919740 },
  wifi_rssi: { state: -40, timestamp: 1744376041 },
  poweron: { state: true, timestamp: 1744515486 },
  lifetime: { state: 3, timestamp: 1744573637 },
  timeron: { state: { ts: 20, du: 0 }, timestamp: null },
  mode: { state: 'auto-regular', timestamp: 1744494458 },
  mcuon: { state: true, timestamp: 1743044998 },
  network_latency: { state: 728154162, timestamp: 1744376041 },
  module_hardware_model: { state: 'PAI-051', timestamp: 1744376041 },
  mcu_firmware_version: { state: '1.0.51', timestamp: 1742919740 },
  module_hardware_mac: { state: '00:1c:c2:60:48:8c', timestamp: 1744376041 },
  muteon: { state: false, timestamp: 1742919740 },
  mcu_hardware_model: { state: '001', timestamp: 1742919740 },
  wifi_ssid: { state: 'ATTnQZmVvS', timestamp: 1742919740 },
  windlevel: { state: 1, timestamp: 1744572474 },
  netionicon: { state: false, timestamp: 1742919740 },
  lightsenval: { state: -1, timestamp: 1744515556 },
  wrong: { state: 0, timestamp: 1744494223 },
  module_firmware_version: { state: '1.2.22', timestamp: 1744376041 },
  aq: { state: 1, timestamp: 1744577780 },
  connected: { state: true, timestamp: 1744376041 },
  timeroff: { state: { ts: 20, du: 0 }, timestamp: null },
  pm25: { state: 1, timestamp: 1744577780 },
  aqi: { state: 100, timestamp: 1744577780 },
  ledalwayson: { state: true, timestamp: 1744515525 },
  childlockon: { state: false, timestamp: 1742919740 },
  dispmode: { state: 'pm25', timestamp: 1742919740 }
}
TypeError: Cannot read properties of undefined (reading 'items')
    at new FanAccessory (/var/lib/homebridge/node_modules/homebridge-dreo/src/accessories/FanAccessory.ts:43:8)
    at DreoPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-dreo/src/platform.ts:174:11)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)

**Comment by bshaheen1** [comment]
Same problem with the Dreo Smart Air Purifier Macro 505S.  I just added this device to my Dreo setup and now my Dreo Homebridge plugin crashes and restarts in a non-stop cycle.  Would love to see support for these air purifiers.

**Device: Dreo Smart Air Purifier Macro 505S
Repeating Log:**

[8/8/2025, 2:40:42 PM] [Dreo Platform] Restarting Process...
[8/8/2025, 2:40:42 PM] [Dreo Platform] Launched child bridge with PID 13674
[8/8/2025, 2:40:42 PM] Registering platform 'homebridge-dreo.DreoPlatform'
[8/8/2025, 2:40:42 PM] [Dreo Platform] Loaded homebridge-dreo v4.1.0 child bridge successfully
[8/8/2025, 2:40:42 PM] Loaded 1 cached accessories from cachedAccessories.0E43DD9D8D76.
[8/8/2025, 2:40:42 PM] [Dreo Platform] Loading accessory from cache: DREO Fan
[8/8/2025, 2:40:43 PM] Homebridge v1.11.0 (HAP v0.13.1) (Dreo Platform) is running on port 55593.
Failed to create listener for avahi-daemon server state. The system will not be notified about restarts of avahi-daemon and will therefore stay undiscoverable in those instances. Error message: Error: No such interface found
[8/8/2025, 2:40:43 PM] [Dreo Platform] Country: US
[8/8/2025, 2:40:43 PM] [Dreo Platform] Region: NA
[8/8/2025, 2:40:43 PM] [Dreo Platform] Restoring existing accessory from cache: DREO Fan
[8/8/2025, 2:40:43 PM] [Dreo Platform] Adding new accessory: Air Purifier
TypeError: Cannot read properties of undefined (reading 'items')
    at new FanAccessory (/volume1/homebridge/node_modules/homebridge-dreo/src/accessories/FanAccessory.ts:43:8)
    at DreoPlatform.discoverDevices (/volume1/homebridge/node_modules/homebridge-dreo/src/platform.ts:174:11)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[8/8/2025, 2:40:43 PM] [Dreo Platform] Child bridge process ended
[8/8/2025, 2:40:43 PM] [Dreo Platform] Process Ended. Code: 1, Signal: null


I tried uninstalling and installing again, before I knew this was a known issue, and now I cannot even add it back as an accessory to my Home in HomeKit, so I've lost HomeKit access to my fan that worked prior to adding the air purifier.

Let me know if there's anything else I can do or provide to help with adding support for this.
