### ISSUE TITLE
Support Dreo Pedestal Fan

### ISSUE THREAD

**Issue by den1k** [zyonse/homebridge-dreo#9]
**Is your feature request related to a problem? Please describe:**
this fan is not yet supported https://www.dreo.com/products/portable-pedestal-fan

**Comment by zyonse** [comment]
Do you have the device?

**Comment by den1k** [comment]
Yes

**Comment by zyonse** [comment]
What happens when you run the plugin? Does it give you an error?

**Comment by den1k** [comment]
It works. I Just don’t see the fan as an accessory.

**Comment by zyonse** [comment]
Can you post the homebridge console output?

**Comment by den1k** [comment]
Sure,

initially

```
[6/13/2023, 2:15:31 PM] [midea-air] SendCommand ([updateValues] attempt 1/2) request failed: Error: getaddrinfo EAI_AGAIN mapp.appsmb.com
[6/13/2023, 2:15:31 PM] [midea-air] [updateValues] Error sending the command: undefined. Trying to re-login before re-issuing command...
[6/13/2023, 2:15:41 PM] [midea-air] [updateValues] re-login attempt failed
[6/13/2023, 2:16:01 PM] [midea-air] SendCommand ([updateValues] attempt 1/2) request failed: Error: getaddrinfo EAI_AGAIN mapp.appsmb.com
[6/13/2023, 2:16:01 PM] [midea-air] [updateValues] Error sending the command: undefined. Trying to re-login before re-issuing command...
```

and then

```
[6/13/2023, 4:52:09 PM] [Dreo Platform] error retrieving token: AxiosError: getaddrinfo EAI_AGAIN app-api-us.dreo-cloud.com
    at Function.AxiosError.from (/volume1/homebridge/node_modules/homebridge-dreo/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/volume1/homebridge/node_modules/homebridge-dreo/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:527:28)
    at ClientRequest.eventHandlers.<computed> (/volume1/homebridge/node_modules/homebridge-dreo/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  hostname: 'app-api-us.dreo-cloud.com',
  syscall: 'getaddrinfo',
  code: 'EAI_AGAIN',
  errno: -3001,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json; charset=UTF-8',
      ua: 'dreo/2.0.7 (sdk_gphone64_x86_64;android 13;Scale/2.625)',
      lang: 'en',
      'accept-encoding': 'gzip',
      'user-agent': 'okhttp/4.9.1',
      'Content-Length': '283'
    },
    params: { timestamp: 1686693119734 },
    method: 'post',
    url: 'https://app-api-us.dreo-cloud.com/api/oauth/login',
    data: '{"client_id":"<hidden>","client_secret":"<hidden>","email":"<hidden>","encrypt":"ciphertext","grant_type":"email-password","himei":"<hidden>","password":"<hidden>","scope":"all"}'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/api/oauth/login?timestamp=1686693119734',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      lookup: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'app-api-us.dreo-cloud.com',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/api/oauth/login',
      search: '?timestamp=1686693119734'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 283,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /api/oauth/login?timestamp=1686693119734 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json; charset=UTF-8\r\n' +
        'ua: dreo/2.0.7 (sdk_gphone64_x86_64;android 13;Scale/2.625)\r\n' +
        'lang: en\r\n' +
        'accept-encoding: gzip\r\n' +
        'user-agent: okhttp/4.9.1\r\n' +
        'Content-Length: 283\r\n' +
        'Host: app-api-us.dreo-cloud.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/oauth/login?timestamp=1686693119734',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'app-api-us.dreo-cloud.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://app-api-us.dreo-cloud.com/api/oauth/login?timestamp=1686693119734',
    [Symbol(kCapture)]: false
  },
  cause: Error: getaddrinfo EAI_AGAIN app-api-us.dreo-cloud.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'app-api-us.dreo-cloud.com'
  }
}
[6/13/2023, 4:52:09 PM] [Dreo Platform] Authentication error: Server returned invalid access_token
[6/13/2023, 4:52:09 PM] [Dreo Platform] Make sure your email/password are correct
```

Email and password are correct. I confirmed by logging out on mobile and back in. I use one password so no typo incorrectness. also double checked.

**Comment by zyonse** [comment]
The first set of logs is from the midea-air plugin and it's throwing the same error. Make sure you don't have any internet issues.

**Comment by den1k** [comment]
You're right, I did have an internet outage a few days back. Ignore those logs, homebridge has been working most of the time

**Comment by zyonse** [comment]
Is the device working now?

**Comment by den1k** [comment]
No, basically nothing is showing up in accessories in homebridge

**Comment by den1k** [comment]
oh interesting. I'm seeing that it does show up in homekit. Not home right now but I will investigate

**Comment by den1k** [comment]
Okay just tested. Controls are only fan speed. No tilt or sleep. And It’s
not working

**Comment by zyonse** [comment]
@den1k Does it respond to the controls in HomeKit? Or is there an error that it gives in homebridge?

**Comment by den1k** [comment]
I’m currently out of country so I can’t check. As far as I remember it
simply did not work and also did not log an error.

**Comment by den1k** [comment]
I'm not sure if anything changed but when I got back home I had to restart homebridge because my midea AC had stopped responding and that resolved the issue with the dreo fan. it works great now. thanks @zyonse!!
